# Generated by Django 4.1.7 on 2023-02-15 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0002_alter_productcategory_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productcategory",
            name="slug",
            field=models.SlugField(blank=True, null=True),
        ),
    ]
