# Generated by Django 4.1.7 on 2023-02-22 14:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0003_alter_shopcategory_slug"),
        ("product", "0003_remove_product_category_delete_productcategory"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="shop",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="shop",
                to="shop.shop",
            ),
        ),
    ]
