# Generated by Django 4.1.7 on 2023-02-20 05:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopcategory',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child', to='shop.shopcategory'),
        ),
        migrations.AddField(
            model_name='shopcategory',
            name='slug',
            field=models.SlugField(default=0),
            preserve_default=False,
        ),
    ]
