# Generated by Django 4.1.7 on 2023-02-22 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_shopcategory_parent_shopcategory_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopcategory',
            name='slug',
            field=models.SlugField(blank=True),
        ),
    ]
