# Generated by Django 4.1.7 on 2023-02-24 04:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0007_alter_product_category"),
        ("shop", "0003_alter_shopcategory_slug"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="ShopCategory",
            new_name="Category",
        ),
        migrations.AlterModelOptions(
            name="category",
            options={"verbose_name": "Category", "verbose_name_plural": "Categories"},
        ),
        migrations.AlterModelTable(
            name="category",
            table="category",
        ),
    ]
